apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: simple-kube-sync
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: simple-kube-sync
            image: ducas/simple-kube-sync:v0.1-alpha
            env:
            - name: GIT_REPO
              value: __GIT_REPO__
          restartPolicy: OnFailure
